### ISSUE TITLE
how to set countdown time with different color from time to time

### ISSUE THREAD

**Issue by hoangnam714** [pawello2222/WidgetExamples#10]
i am trying to change the color of text by 1s interval, with 1s being 1 different color, how to deal with get time line, i tried gnwgs to edit with countdown widget but nnos only works first 3 minutes

**Comment by pawello2222** [comment]
@hoangnam714 

SwiftUI widgets don't support fast refreshing. Please see [Keeping a widget up to date](https://developer.apple.com/documentation/widgetkit/keeping-a-widget-up-to-date).

> A widget’s budget applies to a 24-hour period. WidgetKit tunes the 24-hour window to the user’s daily usage pattern, which means the daily budget doesn’t necessarily reset at exactly midnight. For a widget the user frequently views, a daily budget typically includes from 40 to 70 refreshes. This rate roughly translates to widget reloads every 15 to 60 minutes, but it’s common for these intervals to vary due to the many factors involved.
