### ISSUE TITLE
Manage and refresh widget without opening app

### ISSUE THREAD

**Issue by aakash-patel-dev** [pawello2222/WidgetExamples#12]
Basically, need to manage widget based on silent push-notification, please share your review 
@pawello2222

**Comment by aakash-patel-dev** [comment]
when app is in kill state and refresh the widget

**Comment by pawello2222** [comment]
Hi @aakash-patel-dev 

Apologies for the late response.

I haven't tested the below solution but you can try adding:

```
WidgetCenter.shared.reloadTimelines(ofKind: <WIDGET_KIND>)
```

to [didReceiveRemoteNotification](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application) in the AppDelegate:

````
application(_:didReceiveRemoteNotification:fetchCompletionHandler:)
```
