### ISSUE TITLE
Compilation error: Type 'Binding<NavigationSplitViewVisibility>' has no member 'doubleColumn'

### ISSUE THREAD

**Issue by ALexanderLonsky** [pawello2222/WidgetExamples#13]
Hi, I'm currently on the `ios17-refactor` branch, and it's not compiling. It requires passing the binding. So, using `.constant(.doubleColumn)` instead of just `.doubleColumn` solves the issue.

**Comment by pawello2222** [comment]
Thanks, I've just fixed the issue and also merged the branch to main.
