### ISSUE TITLE
Digital clock 如何每秒更新时间呢？

### ISSUE THREAD

**Issue by linghugoogle** [pawello2222/WidgetExamples#15]
TimelineProvider.getTimeline对更新频率，entries数组的长度都有显示。
请问：如何每秒更新时间呢？
非常感谢🙏

**Comment by pawello2222** [comment]
Hi @linghugoogle 

If you'd like me to answer the question please ask in English as unfortunately I don't speak Chinese.

If you're asking how to refresh the widget every second then, for now, it's not possible. Please refer to [Keeping a widget up to date](https://developer.apple.com/documentation/widgetkit/keeping-a-widget-up-to-date).
