### ISSUE TITLE
iOS17的小组件时间线刷新问题

### ISSUE THREAD

**Issue by shenchunxing** [pawello2222/WidgetExamples#16]
你好。这是iOS17的小组件时间线接口，我需要先显示正在加载页面，然后网络请求后，显示成功页面，.但是发现只显示了正在加载页面，而不会再次刷新进入成功页面。如何做到我想要的效果，感谢！！！
 func timeline(for configuration: EmergencyAlarmWidgetIntent, in context: Context) async -> Timeline<Entry> {
//通过设置枚举来区分页面
   switch AlarmIntentType.type {
   case .ringingAlarm, //正在报警
      // 这里是异步的网络请求代码
      soundAlarm(context: context) { result in 
         //修改状态，显示成功页面
         AlarmIntentType.type = .alarmSuccess 
            return Timeline(entries:[Entry(date:Date()),type: AlarmIntentType.type)], policy: .never)
      }
     //显示正在加载页面
       return Timeline(entries:[Entry(date:Date()),type: AlarmIntentType.type)], policy: .never)
}

**Comment by pawello2222** [comment]
Hi @shenchunxing  

If you'd like me to answer the question please ask in English as unfortunately I don't speak Chinese.

Please refer to the [NetworkWidget+Provider](https://github.com/pawello2222/WidgetExamples/blob/main/Widgets/NetworkWidget/NetworkWidget%2BProvider.swift) for an example how to perform network requests and pass the result to the widget entry view.
