### ISSUE TITLE
Play/Pause audio from widget 

### ISSUE THREAD

**Issue by Volodymyr-13** [pawello2222/WidgetExamples#18]
Hey @pawello2222 

Thanks for this amazing repo! It helps a lot.

Currently, I'm trying to implement ability of control music in my main app from widget.
So far I found a lot of problems in this direction:

- https://forums.developer.apple.com/forums/thread/736445
- https://forums.developer.apple.com/forums/thread/738477
- https://stackoverflow.com/questions/76656439/how-to-add-appintent-to-app-target-and-use-it-in-an-interactive-widget
- https://stackoverflow.com/questions/76566373/why-dont-interactive-buttons-in-ios-17-widget-call-appintent-perform-when-the

So I was wondering if you could share an example specially for audio playback?

**Comment by pawello2222** [comment]
Hey @Volodymyr-13 

Thanks, it's an interesting use case.

Here's the widget: [AudioPlaybackWidget](https://github.com/pawello2222/WidgetExamples/tree/main/Widgets/AudioPlaybackWidget).

Please bear in mind it's just an example - to avoid unnecessary complexity I decided to limit the interaction to play/pause actions. Let me know if it answers your question.
