### ISSUE TITLE
Data sharing from iOS app to Lock Screen widget and Watch widget

### ISSUE THREAD

**Issue by BigabilityLiu** [pawello2222/WidgetExamples#5]
Hi bro, thanks for these examples.

I'm working on iOS 16 / watchOS 9 Widget these days.
Before, I have a Watch Complications (ClockKit), it gets data from iOS app every 10 mins through WatchConnectivity, it works well.
But on watch 9, it needed to migrate to WidgetKit ([Migrating ClockKit complications to WidgetKit](https://developer.apple.com/documentation/widgetkit/converting-a-clockkit-app)), then WatchConnectivity doesn't work anymore, shows error "Companion app is not installed".
I have also tried share data on  App Group UserDefault between iOS app and Watch Widget,  but when read data on widget it shows error "[User Defaults] Couldn't read values in CFPrefsPlistSource<0x...> (Domain: group.com...., User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd"

I'm trying to use intent to configure/update widget data ([Making a Configurable Widget](https://developer.apple.com/documentation/widgetkit/making-a-configurable-widget)), but I'm not sure if it can update my Widget every 10 mins, or Intents is not for this use at all. 

If not,  the only way is use URLSession to request  data from http server.

So do you have any suggestions base on your experience, 

Thank you from your time

**Comment by BigabilityLiu** [comment]
Thank you for your kindly response,

Actually the main thing I want to discuss is the way of data sharing between iOS App and Widget.

I'm going to close this issue for now. I'll be back if i find a better way to share data further.

**Comment by pawello2222** [comment]
Please see the [AppGroupWidget](https://github.com/pawello2222/WidgetExamples/tree/main/WidgetExtension/AppGroupWidget) as an example of how to share data between the App and the Widget (using `UserDefaults` of `FileManager`).
