### ISSUE TITLE
Do you need to create a separate widgets project to support ios16 or do you want to add this directly to the previous widgets

### ISSUE THREAD

**Issue by purgebug** [pawello2222/WidgetExamples#6]
// Uncomment below for iOS 16
        // WidgetBundle4().body 
So what's going to happen here? Is a new ios16 project compatible? Again, let's put a little bit of conditionality here.

The widger Ios14 is abnormal

**Comment by pawello2222** [comment]
I've updated the project to the minimum deployment target of iOS 16.

The old iOS 14 compatible project is still accessible on the [ios14](https://github.com/pawello2222/WidgetExamples/tree/ios14) branch.

**Comment by purgebug** [comment]
You got me wrong, it's to be compatible with both ios14 and IOS16
Whether the lock screen widget is displayed in IOS14,
Again, we're going to create two separate projects, one for ios14 and one for ios16 that will support lock screen widgets separately

**Comment by pawello2222** [comment]
I don't think you can add conditionality (`if #available`) in the widget's `body`, although I may be wrong here.
