### ISSUE TITLE
URLImageView Cache images

### ISSUE THREAD

**Issue by purgeyao** [pawello2222/WidgetExamples#7]
Your example is great, but the URLImageView example can add an image cache, so if it's the same URL, it doesn't load the network

**Comment by pawello2222** [comment]
I've added a new example of how to load an image (this time from the TimelineProvider) and I've included cache as well: [URLCachedImageWidget](https://github.com/pawello2222/WidgetExamples/tree/main/WidgetExtension/URLCachedImageWidget).
