### ISSUE TITLE
Countdown widget does not show as Ideal effect😭

### ISSUE THREAD

**Issue by ColdLessLee** [pawello2222/WidgetExamples#8]
in my case for countdown widget, when I declare a **for-loop with 60 * 24 second times**, the widget will not render on the real device, it shows me a skeleton 🥹

**Comment by liyanhongCN** [comment]
在iOS 16 设备上， 我也遇到了这个问题，请问怎么解决啊

**Comment by pawello2222** [comment]
Hi,

Apologies for the late response.

Widgets can only be refreshed a certain number of times per day. If there's a problem with refreshing it's usually one of the following two:
- refreshing too often - a widget usually don't have more than 40-70 refreshes per day (can be less)
- adding too many entries to the timeline - the solution is to refresh the timeline more often, e.g. not every day, but every hour (just remember not to refresh the widget too often and not to add too many entries at once)

For more information please refer to [Keeping a widget up to date](https://developer.apple.com/documentation/widgetkit/keeping-a-widget-up-to-date).
