### ISSUE TITLE
大佬，知道怎么支持播放GIF吗？在小组件中怎么实现啊

### ISSUE THREAD

**Issue by Jdb156158** [pawello2222/WidgetExamples#9]

**Comment by chdo002** [comment]
同问，已经有app实现了动画播放，像top widget ，dtd playlist

**Comment by pawello2222** [comment]
@Jdb156158 @chdo002 

Generally widgets aren't designed to have animations (at least for now). If it changes, the relevant API will be added (like in the case of interactive widgets).

I'm aware of two ways of animating widgets:

1. Private API

An example can be ` _clockHandRotationEffect` as described in [this issue](https://github.com/pawello2222/WidgetExamples/issues/1#issuecomment-1064194182). 

You may have to build a library with Xcode 13, so it's available in later versions.

_(There might be more hidden methods - feel free to look for yourself.)_

2. Custom fonts 

You can create a timer that will change every second. 
```swift
Text(.now, style: .timer)
```

In theory providing a custom font as described in [this thread](https://developer.apple.com/forums/thread/720640?answerId=744938022#744938022) should allow implementing gif-style animations.

**Comment by Jdb156158** [comment]
> 同问，已经有app实现了动画播放，像top widget ，dtd playlist

@chdo002 ，加我微 JDB118158168可以一起讨论

**Comment by pawello2222** [comment]
Added [AnalogClockWidget](https://github.com/pawello2222/WidgetExamples/tree/main/Widgets/AnalogClockWidget) in version 1.1.0. This widget uses an example private xcframework that may not necessarily pass Apple Review. 

The tutorial how to create an xcframework with ClockHandRotationEffect can be found [here](https://github.com/everettjf/Xcode13ClockHandRotationEffectModifier).
